# Generated by Django 5.2.2 on 2025-06-25 15:01

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [ TrigramExtension() ]
